### ISSUE TITLE
Unity (2017.3.0f3) Build error

### ISSUE THREAD

**Issue by NDRWhun** [Ben1138/Unity-SWBF2-Import#1]
"Assets/SWBF2Import/SWBF2Import.cs(5,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?"

When I try to build it, this error coming up. Is that script able to build, or it's just imports the things?

Thank you anyway!
(Sorry I'm lame in programming)

**Problem solved. It was my bad. SWBFImporter.cs need to be in Editor folder. Please update the Readme file. :) Thank's for the tool! It's very Cool!

**Comment by Ben1138** [comment]
No prob ;)
Overall, the readme is not up-to-date.
Maybe I will do a DLL-Plugin version of this in the future.
