### ISSUE TITLE
LibSWBF2

### ISSUE THREAD

**Issue by Ghost1138** [Ben1138/Unity-SWBF2-Import#6]
SOLVED

I've extracted the SWBF2Import folder into my Assets/ directory but when I load my project I get the error CS0246

Assets/SWBF2Import/SWBF2Import.cs(6,7): error CS0246: The type or namespace name 'LibSWBF2' could not be found. Are you missing an assembly reference?

I've seen there has been a similar issue which was solved by sending SWBF2Import.cs into the Editor folder, but it didn't solve my problem. Am I doing something wrong? How can I solve this?

My Unity version: 2017.3.0f3 (64-bit)

EDIT: I've updated Unity to it's latest version, this fixed the issue. Sorry for bothering you.

**Comment by Ben1138** [comment]
No Problem ;)
