### ISSUE TITLE
Unable to load terrain

### ISSUE THREAD

**Issue by tanner72** [Ben1138/Unity-SWBF2-Import#7]
I'm extremely new to unity so this could be an obvious fix, but when I attempt to load my .wld file, under Terrain Info it says "No Terrain available!" and when I try to import the layers an error pops up saying "ArgumentNullException: Value cannot be null"

Also when I try importing .msh files the objects appear blank. If there's a solution to this I would massively appreciate it because this seems like it would make importing .msh files wayy easier. I'm using version 2019.2.3.f1 on Mac if that helps at all.

**Comment by Ben1138** [comment]
Yeah the old importer was unfinished and is now deprecated. There is a new attempt, but I've not developed on it for months. You can also take a look at https://github.com/Ben1138/MSH2FBX for converting meshes

**Comment by tanner72** [comment]
Gotcha. Thanks a ton!

**Comment by tanner72** [comment]
Thanks a ton!
