### ISSUE TITLE
Shader material

### ISSUE THREAD

**Issue by Ianmcmill** [Ben1138/Unity-SWBF2-Import#8]
I'm trying to get wld files into Unity. In the Importers' options, there is a slot for Materials. 
Which material goes in here? Is there a predefined shader material from SWBF2?

**Comment by Ianmcmill** [comment]
creating a defalt material solves the issue.

**Comment by Ben1138** [comment]
Yeah exactly. You can specify a Material (Shader) to use for all imported meshes.
